name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: install cowsay      
        run: sudo apt-get install cowsay -y
        
      - name: Execute shell cmd
        run: cowsay -f dragon "Run for cover I'm a Dragon....RAWRRR">> dragon.txtOB

      - name: sleep for 30 seconds
        run: sleep 30

    test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: sleep for 10s
        run: sleep 10

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

    deploy_job_3:
      needs: test_job_2
      runs-on: ubuntu-latest
      steps: 
      - name: Read file
        run: cat dragon.txt



      

